/*	Angshuman Ghosh		2017CS01	Date:23-10-2017

Program to catch termination signals generated by the parent in the child process

*/


#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>



void term(int sig){
	
	//	ignore the signals during the routine

	signal(SIGINT, SIG_IGN);
	signal(SIGHUP, SIG_IGN);
	signal(SIGTERM, SIG_IGN);

	//	catch the appropriate signal

	switch(sig){

		case SIGQUIT:
			printf("\nCaught SIGQUIT signal .... exiting\n");
			exit(0);
			break;
		case SIGINT:
			printf("\nCaught SIGINT signal\n");
			break;
		case SIGHUP:
			printf("\nCaught SIGHUP signal\n");
			break;
		case SIGTERM:
			printf("\nCaught SIGTERM signal\n");
			break;

	}

	//	reinstall the signals

	signal(SIGINT, term);
	signal(SIGHUP, term);
	signal(SIGTERM, term);
}


int main(){

	int rv;
	pid_t pid;

	pid = fork();		// create child process

	switch(pid){

		case -1:
			printf("Child spawn unsuccessful\n");
			return 1;
		case 0:					//	install the signals in child
			signal(SIGINT, term);
			signal(SIGHUP, term);
			signal(SIGTERM, term);
			signal(SIGQUIT, term);

			printf("Child started executing\n");

			while(1);			//	child waits for signals created by parent

		default:				//	parent generates kill signals for child
			sleep(3);
			kill(pid, SIGINT);
			sleep(3);
			kill(pid, SIGHUP);
			sleep(3);
			kill(pid, SIGTERM);
			sleep(3);
			kill(pid, SIGQUIT);


	}

	wait(&rv);

	printf("Child returned exit code : %d\n", WEXITSTATUS(rv));

	return 0;
}
